apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  magic-word: {{ .Values.env.MAGIC_WORD | default "" | b64enc | quote }}
