name: Test Conditional Branch Workflow

on:
  push:
    branches:
      - '**' # Allow the workflow to trigger on all branches
  workflow_dispatch:

jobs:
  test-branch-condition:
    runs-on: ubuntu-latest
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch) || startsWith(github.ref, 'refs/heads/hotfix/')
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Display branch information
        run: |
          echo "Triggered by branch: ${{ github.ref }}"
          echo "Default branch: ${{ github.event.repository.default_branch }}"

      - name: Run job for allowed branches
        run: |
          echo "This job runs only for the default branch or hotfix branches."
